vh = float(input('Quanto você ganha por hora? '))
qh = int(input('Quantas horas você trabalhou esse mês? '))
sb = float(vh*qh)
ir = float(11%sb)
inss = float(8%sb)
sin = float(5%sb)
sl = float(76%sb)

print('Aqui estão suas informações:')
print(f'> Salário bruto: {sb}')
print(f'> Quanto pagou de INSS: {inss}')
print(f'> Quanto pagou ao Sindicato: {sin}')
print(f'> Salário líquido: {sl}')